# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ActiveStorage::CleanupBlobsJob`.
# Please instead update this file by running `bin/tapioca dsl ActiveStorage::CleanupBlobsJob`.

class ActiveStorage::CleanupBlobsJob
  class << self
    sig { returns(T.any(ActiveStorage::CleanupBlobsJob, FalseClass)) }
    def perform_later; end

    sig { void }
    def perform_now; end
  end
end
