# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Lookbook::BaseComponent`.
# Please instead update this file by running `bin/tapioca dsl Lookbook::BaseComponent`.

class Lookbook::BaseComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
