# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `graphql-pagination` gem.
# Please instead update this file by running `bin/tapioca gem graphql-pagination`.


class GraphQL::Schema::Object < ::GraphQL::Schema::Member
  extend ::GraphqlPagination::CollectionType
end

# source://graphql-pagination//lib/graphql_pagination/version.rb#1
module GraphqlPagination; end

# source://graphql-pagination//lib/graphql_pagination/collection_base_error.rb#2
class GraphqlPagination::CollectionBaseError < ::StandardError
  # source://graphql-pagination//lib/graphql_pagination/collection_base_error.rb#3
  def message; end
end

# source://graphql-pagination//lib/graphql_pagination/collection_metadata_type.rb#2
class GraphqlPagination::CollectionMetadataType < ::GraphQL::Schema::Object
  extend ::GraphQL::Schema::Member::HasInterfaces::ClassConfigured::InheritedInterfaces
end

# source://graphql-pagination//lib/graphql_pagination/collection_type.rb#2
module GraphqlPagination::CollectionType
  # source://graphql-pagination//lib/graphql_pagination/collection_type.rb#3
  def collection_type(collection_base: T.unsafe(nil), metadata_type: T.unsafe(nil)); end
end

# source://graphql-pagination//lib/graphql_pagination/version.rb#2
GraphqlPagination::VERSION = T.let(T.unsafe(nil), String)
