# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `neatjson` gem.
# Please instead update this file by running `bin/tapioca gem neatjson`.

# source://neatjson//lib/neatjson.rb#2
module JSON
  extend ::Bootsnap::CompileCache::JSON::Patch

  class << self
    # Generate the JSON string representation for an object,
    # with a variety of formatting options.
    #
    # The lambda for the `sort` option will be passed the string name of the key, the value, and the hash for the object being sorted.
    # The values returned for all keys must be all comparable, or an error will occur.
    #
    # @author Gavin Kistner <!@phrogz.net>
    # @option opts
    # @option opts
    # @option opts
    # @option opts
    # @option opts
    # @option opts
    # @option opts
    # @option opts
    # @option opts
    # @option opts
    # @option opts
    # @option opts
    # @option opts
    # @option opts
    # @option opts
    # @option opts
    # @option opts
    # @option opts
    # @option opts
    # @option opts
    # @option opts
    # @option opts
    # @option opts
    # @option opts
    # @option opts
    # @param object [Object] the object to serialize
    # @param opts [Hash] the formatting options
    # @return [String] the JSON representation of the object.
    #
    # source://neatjson//lib/neatjson.rb#38
    def neat_generate(object, opts = T.unsafe(nil)); end
  end
end
