# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Eventqr::EventMailer`.
# Please instead update this file by running `bin/tapioca dsl Eventqr::EventMailer`.

class Eventqr::EventMailer
  class << self
    sig { params(event: ::Eventqr::Event).returns(::ActionMailer::MessageDelivery) }
    def qr_code_generated_email(event); end
  end
end
