# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `RSpotify::AlbumSerializer`.
# Please instead update this file by running `bin/tapioca dsl RSpotify::AlbumSerializer`.


class RSpotify::AlbumSerializer
  sig { returns(RSpotify::Album) }
  def album; end
end
