projects:
  schema:
    schema: "http://localhost:3000/graphql"
    extensions:
      codegen:
        generates:
          "graphql/schema.graphql":
            plugins: ["schema-ast"]
  helpers:
    schema: graphql/schema.graphql
    documents: app/queries/*.graphql
    extensions:
      codegen:
        generates:
          "app/helpers/graphql/types.generated.ts":
            plugins: ["typescript"]
            config:
              scalars:
                DateTime: string
                Date: string
          "app/helpers/graphql/operations.generated.ts":
            preset: import-types
            presetConfig:
              typesPath: ./types.generated
            plugins:
              - typescript-operations
              - typed-document-node
            config:
              avoidOptionals:
                field: true
              omitOperationSuffix: true
              preResolveTypes: false
          "app/helpers/apollo/introspection.generated.ts":
            plugins: ["fragment-matcher"]
          "app/helpers/apollo/clientHelpers.generated.ts":
            plugins: ["typescript-apollo-client-helpers"]
