# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://docs.rubocop.org/rubocop/configuration

require:
  - rubocop-graphql
  - rubocop-performance
  - rubocop-rails
  - rubocop-sorbet

inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  NewCops: enable
  Exclude:
    - .devcontainer/**/*
    - .husky/**/*
    - db/schema.rb
    - bin/**/*
    - log/**/*
    - node_modules/**/*
    - public/**/*
    - tmp/**/*
    - sorbet/rbi/annotations/**/*
    - sorbet/rbi/dsl/**/*
    - sorbet/rbi/gems/**/*
    - sorbet/rbi/sorbet-typed/**/*
    - storage/**/*
    - vendor/**/*
    - config.ru
    - Gemfile
    - Rakefile
  Include:
    - "**/*.rb"
    - "**/*.rbi"
    - "**/*.gemfile"
    - "**/*.gemspec"
    - "**/*.rake"
    - "**/*.ru"
    - "**/Gemfile"
    - "**/Rakefile"

Lint/MissingCopEnableDirective:
  Enabled: false
Lint/Void:
  Enabled: false

Layout/ArgumentAlignment:
  EnforcedStyle: with_first_argument
Layout/BlockAlignment:
  EnforcedStyleAlignWith: start_of_block
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/FirstArgumentIndentation:
  Enabled: true
# Layout/MultilineMethodCallIndentation:
Layout/LineLength:
  Max: 80
  AllowedPatterns: ["# rubocop:disable"]

Naming/InclusiveLanguage:
  Enabled: false

Style/AndOr:
  EnforcedStyle: conditionals
Style/ClassAndModuleChildren:
  Enabled: false
Style/ClassMethodsDefinitions:
  Enabled: false
Style/CommandLiteral:
  EnforcedStyle: backticks
Style/Documentation:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
Style/SymbolArray:
  EnforcedStyle: percent
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/WordArray:
  EnforcedStyle: percent

Sorbet/FalseSigil:
  Enabled: false
Sorbet/ValidSigil:
  MinimumStrictness: "ignore"

Rails/Delegate:
  Enabled: false
Rails/LexicallyScopedActionFilter:
  Enabled: false
Rails/HasAndBelongsToMany:
  Enabled: false
Rails/I18nLocaleTexts:
  Enabled: false

GraphQL/ArgumentDescription:
  Enabled: false
GraphQL/FieldDescription:
  Enabled: false
GraphQL/ObjectDescription:
  Enabled: false
