# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://docs.rubocop.org/rubocop/configuration

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-sorbet
  - rubocop-capybara

inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  NewCops: enable
  Exclude:
    - .github/**/*
    - .husky/**/*
    - .vscode/**/*
    - db/schema.rb
    - bin/**/*
    - log/**/*
    - node_modules/**/*
    - public/**/*
    - tmp/**/*
    - sorbet/rbi/annotations/**/*
    - sorbet/rbi/dsl/**/*
    - sorbet/rbi/gems/**/*
    - sorbet/rbi/sorbet-typed/**/*
    - storage/**/*
    - vendor/**/*
    - config.ru
    - Gemfile
    - Rakefile
  Include:
    - "**/*.rb"
    - "**/*.rbi"
    - "**/*.gemfile"
    - "**/*.gemspec"
    - "**/*.rake"
    - "**/*.ru"
    - "**/Gemfile"
    - "**/Rakefile"
  CacheRootDirectory: "tmp/cache/rubocop"

Layout/LineLength:
  Max: 80
  AllowedPatterns:
    - "\\A\\s*(remote_)?test(_\\w+)?\\s.*(do|->)(\\s|\\Z)"
    - "\\A\\s*def test_\\w+\\s*\\Z"
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/DotPosition:
  EnforcedStyle: leading
Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/FirstArrayElementLineBreak:
  Enabled: true
  AllowMultilineFinalElement: true
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/FirstHashElementLineBreak:
  Enabled: true
Layout/FirstMethodArgumentLineBreak:
  Enabled: true
  AllowMultilineFinalElement: true
Layout/IndentationConsistency:
  Enabled: true
Layout/LineContinuationLeadingSpace:
  Enabled: true
Layout/LineContinuationSpacing:
  Enabled: true
Layout/LineEndStringConcatenationIndentation:
  Enabled: true
  EnforcedStyle: indented
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  IndentationWidth: 2
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/SpaceBeforeBrackets:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: true
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Sorbet/ValidSigil:
  MinimumStrictness: ignore
