version: "3.9"

services:
  postgres-dev:
    image: postgis/postgis:15-3.3
    volumes:
      - postgres-dev:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  postgres-test:
    image: postgis/postgis:15-3.3
    volumes:
      - postgres-test:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1080:1080
      - 1025:1025

volumes:
  postgres-dev: null
  postgres-test: null
