app = "itskai"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[deploy]
  release_command = "bin/release"

[env]
  RAILS_DEFAULT_URL = "https://itskai.me"
  RAILS_MAILER_FROM = "RoboKai <robot@itskai.me>"
  RAILS_MAILER_REPLY_TO = "Kai <hullo@itskai.me>"
  SPOTIFY_CLIENT_ID = "0a0f796dd227445787b5cc019a749555"
  MAILJET_API_KEY = "71f29dcbbc010c367b0450a44b06e702"
  FULLSTORY_ORG_ID = "o-1CGMZ5-na1"
  GOOGLE_ANALYTICS_MEASUREMENT_ID = "G-MFGZXQLMM9"
  AWS_ACCESS_KEY_ID = "AKIA267OA7D6UCFFUX3B"
  AWS_BUCKET = "itskai"
  AWS_REGION = "us-east-2"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"
