app = "itskai"
primary_region = "sea"
kill_signal = "SIGINT"
kill_timeout = 10

[experimental]
  auto_rollback = true

[deploy]
  release_command = "bin/release"
  strategy = "bluegreen"

[env]
  RAILS_DEFAULT_URL = "https://itskai.me"
  RAILS_MAILER_FROM = "It's Kai <robot@itskai.me>"
  RAILS_MAILER_REPLY_TO = "Kai <hullo@itskai.me>"
  SENTRY_TRACES_SAMPLE_RATE = "0.1"
  SENTRY_PROFILES_SAMPLE_RATE = "0.1"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]
  min_machines_running = 1

[services.concurrency]
  type = "requests"
  hard_limit = 1000
  soft_limit = 100

[[services.ports]]
  port = 80
  handlers = ["http"]
  force_https = true

[[services.ports]]
  port = 443
  handlers = ["tls", "http"]

[[services.http_checks]]
  interval = "15s"
  timeout = "2s"
  grace_period = "10s"
  method = "get"
  path = "/status"
  protocol = "http"

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"
