app = "itskai"
primary_region = "den"
kill_signal = "SIGINT"
swap_size_mb = 1024

[experimental]
  auto_rollback = true

[deploy]
  release_command = "bin/deploy"
  strategy = "bluegreen"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

[services.concurrency]
  type = "requests"
  hard_limit = 1000
  soft_limit = 100

[[services.ports]]
  port = 80
  handlers = ["http"]
  force_https = true

[[services.ports]]
  port = 443
  handlers = ["tls", "http"]

[[services.http_checks]]
  interval = "15s"
  timeout = "2s"
  grace_period = "30s"
  method = "get"
  path = "/up"
  protocol = "http"

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"
