- id: principles_practices
  label: how principles and practices shape peoples lives
- id: showing_up
  label: how important it is to simply show up
- id: surface_area_self_connection
  label: increasing the surface area for self-connection
- id: posture_showing_up
  label: posture and practicing the way you show up for yourself
- id: letting_things_unfold
  label: '"trying" vs "letting things unfold"'
- id: world_needs_you
  label: how the world needs you to come alive
- id: honouring_yourself
  label: honouring yourself in connnection with others
- id: beauty_in_awkwardness
  label: seeing the beauty in your own fear and awkwardness
