# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `AdminParameters`.
# Please instead update this file by running `bin/tapioca dsl AdminParameters`.


class AdminParameters
  sig { returns(T.nilable(::String)) }
  def new_location_access_grant_id; end

  sig { params(value: T.nilable(::String)).returns(T.nilable(::String)) }
  def new_location_access_grant_id=(value); end
end
