# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `AnalyzeObsidianNoteJob`.
# Please instead update this file by running `bin/tapioca dsl AnalyzeObsidianNoteJob`.

class AnalyzeObsidianNoteJob
  class << self
    sig { params(note: ::ObsidianNote).returns(T.any(AnalyzeObsidianNoteJob, FalseClass)) }
    def perform_later(note); end

    sig { params(note: ::ObsidianNote).void }
    def perform_now(note); end
  end
end
