# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ApplicationSerializer`.
# Please instead update this file by running `bin/tapioca dsl ApplicationSerializer`.


class ApplicationSerializer
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule

  sig { returns(T.untyped) }
  def application; end
end
