# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `CleanupStorageJob`.
# Please instead update this file by running `bin/tapioca dsl CleanupStorageJob`.

class CleanupStorageJob
  class << self
    sig { returns(T.any(CleanupStorageJob, FalseClass)) }
    def perform_later; end

    sig { void }
    def perform_now; end
  end
end
