# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Exploration`.
# Please instead update this file by running `bin/tapioca dsl Exploration`.


class Exploration
  include FrozenRecordAttributeMethods

  module FrozenRecordAttributeMethods
    sig { returns(T.untyped) }
    def id; end

    sig { returns(T::Boolean) }
    def id?; end

    sig { returns(T.untyped) }
    def label; end

    sig { returns(T::Boolean) }
    def label?; end
  end
end
