# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `FriendVibecheckNotificationPayloadSerializer`.
# Please instead update this file by running `bin/tapioca dsl FriendVibecheckNotificationPayloadSerializer`.


class FriendVibecheckNotificationPayloadSerializer
  sig { returns(FriendVibecheck) }
  def friend_vibecheck; end
end
