# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ImportJournalEntryBlocksJob`.
# Please instead update this file by running `bin/tapioca dsl ImportJournalEntryBlocksJob`.

class ImportJournalEntryBlocksJob
  class << self
    sig { params(entry: ::JournalEntry).returns(T.any(ImportJournalEntryBlocksJob, FalseClass)) }
    def perform_later(entry); end

    sig { params(entry: ::JournalEntry).void }
    def perform_now(entry); end
  end
end
