# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `JournalEntrySerializer`.
# Please instead update this file by running `bin/tapioca dsl JournalEntrySerializer`.


class JournalEntrySerializer
  sig { returns(JournalEntry) }
  def entry; end
end
