# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `LocationAccessGrantSerializer`.
# Please instead update this file by running `bin/tapioca dsl LocationAccessGrantSerializer`.


class LocationAccessGrantSerializer
  sig { returns(LocationAccessGrant) }
  def grant; end
end
