# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `MessageMailer`.
# Please instead update this file by running `bin/tapioca dsl MessageMailer`.

class MessageMailer
  class << self
    sig do
      params(
        message: ::Message,
        referrer: T.nilable(::ApplicationRecord)
      ).returns(::ActionMailer::MessageDelivery)
    end
    def new_message_email(message:, referrer: T.unsafe(nil)); end
  end
end
