# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `OAuthConnectionSerializer`.
# Please instead update this file by running `bin/tapioca dsl OAuthConnectionSerializer`.


class OAuthConnectionSerializer
  sig { returns(OAuthConnection) }
  def connection; end
end
