# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ObsidianNoteSynchronizationJob`.
# Please instead update this file by running `bin/tapioca dsl ObsidianNoteSynchronizationJob`.

class ObsidianNoteSynchronizationJob
  class << self
    sig { returns(T.any(ObsidianNoteSynchronizationJob, FalseClass)) }
    def perform_later; end

    sig { void }
    def perform_now; end
  end
end
