# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ObsidianNoteAnalysisJob`.
# Please instead update this file by running `bin/tapioca dsl ObsidianNoteAnalysisJob`.

class ObsidianNoteAnalysisJob
  class << self
    sig { params(force: T::Boolean).returns(T.any(ObsidianNoteAnalysisJob, FalseClass)) }
    def perform_later(force: T.unsafe(nil)); end

    sig { params(force: T::Boolean).void }
    def perform_now(force: T.unsafe(nil)); end
  end
end
