# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Resolver`.
# Please instead update this file by running `bin/tapioca dsl Resolver`.

module Resolver
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
