export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** An ISO 8601-encoded date */
  Date: { input: string; output: string; }
  /** An ISO 8601-encoded datetime */
  DateTime: { input: string; output: string; }
  /** Represents untyped JSON */
  JSON: { input: any; output: any; }
};

/** Autogenerated input type of ActivateScottkitSignal */
export type ActivateScottkitSignalInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  type: ScottkitSignalType;
};

/** Autogenerated return type of ActivateScottkitSignal. */
export type ActivateScottkitSignalPayload = {
  __typename?: 'ActivateScottkitSignalPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  success: Scalars['Boolean']['output'];
};

/** Autogenerated input type of AddJournalEntryComment */
export type AddJournalEntryCommentInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  entryId: Scalars['ID']['input'];
  text: Scalars['String']['input'];
};

/** Autogenerated return type of AddJournalEntryComment. */
export type AddJournalEntryCommentPayload = {
  __typename?: 'AddJournalEntryCommentPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  success: Scalars['Boolean']['output'];
};

export type CookieInput = {
  domain: Scalars['String']['input'];
  expirationDate?: InputMaybe<Scalars['Int']['input']>;
  hostOnly: Scalars['Boolean']['input'];
  httpOnly: Scalars['Boolean']['input'];
  name: Scalars['String']['input'];
  path: Scalars['String']['input'];
  sameSite: Scalars['String']['input'];
  secure: Scalars['Boolean']['input'];
  session: Scalars['Boolean']['input'];
  value: Scalars['String']['input'];
};

export type ICloudCredentials = Node & {
  __typename?: 'ICloudCredentials';
  cookies?: Maybe<Scalars['String']['output']>;
  email: Scalars['String']['output'];
  /** ID of the object. */
  id: Scalars['ID']['output'];
  password: Scalars['String']['output'];
  session?: Maybe<Scalars['JSON']['output']>;
};

export type Image = Node & {
  __typename?: 'Image';
  /** ID of the object. */
  id: Scalars['ID']['output'];
  signedId: Scalars['String']['output'];
  url: Scalars['String']['output'];
};


export type ImageUrlArgs = {
  size?: InputMaybe<ImageSize>;
};

export type ImageInput = {
  signedId: Scalars['String']['input'];
};

export enum ImageSize {
  Lg = 'LG',
  Md = 'MD',
  Sm = 'SM'
}

/** Autogenerated input type of ImportCookies */
export type ImportCookiesInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  cookies: Array<CookieInput>;
};

/** Autogenerated return type of ImportCookies. */
export type ImportCookiesPayload = {
  __typename?: 'ImportCookiesPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  success: Scalars['Boolean']['output'];
};

/** Autogenerated input type of ImportJournalEntries */
export type ImportJournalEntriesInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
};

/** Autogenerated return type of ImportJournalEntries. */
export type ImportJournalEntriesPayload = {
  __typename?: 'ImportJournalEntriesPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  success: Scalars['Boolean']['output'];
};

/** Autogenerated input type of ImportObsidianNotes */
export type ImportObsidianNotesInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
};

/** Autogenerated return type of ImportObsidianNotes. */
export type ImportObsidianNotesPayload = {
  __typename?: 'ImportObsidianNotesPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  success: Scalars['Boolean']['output'];
};

export type InputFieldError = {
  __typename?: 'InputFieldError';
  field: Scalars['String']['output'];
  message: Scalars['String']['output'];
};

export type JournalEntry = Node & {
  __typename?: 'JournalEntry';
  content: Array<Scalars['JSON']['output']>;
  /** ID of the object. */
  id: Scalars['ID']['output'];
  modifiedAt: Scalars['DateTime']['output'];
  nextEntryId?: Maybe<Scalars['ID']['output']>;
  startedAt: Scalars['DateTime']['output'];
  title: Scalars['String']['output'];
  url: Scalars['String']['output'];
};

export type Mutation = {
  __typename?: 'Mutation';
  activateScottkitSignal: ActivateScottkitSignalPayload;
  addJournalEntryComment: AddJournalEntryCommentPayload;
  importCookies: ImportCookiesPayload;
  importJournalEntries: ImportJournalEntriesPayload;
  importObsidianNotes: ImportObsidianNotesPayload;
  removeICloudCredentials: RemoveICloudCredentialsPayload;
  removeSpotifyCredentials: RemoveSpotifyCredentialsPayload;
  requestUserEmailVerification: RequestUserEmailVerificationPayload;
  requestUserPasswordReset: RequestUserPasswordResetPayload;
  testMutation: TestMutationPayload;
  updateICloudCredentials: UpdateICloudCredentialsPayload;
  updateUserEmail: UpdateUserEmailPayload;
  updateUserProfile: UpdateUserProfilePayload;
  verifyICloudSecurityCode: VerifyICloudSecurityCodePayload;
};


export type MutationActivateScottkitSignalArgs = {
  input: ActivateScottkitSignalInput;
};


export type MutationAddJournalEntryCommentArgs = {
  input: AddJournalEntryCommentInput;
};


export type MutationImportCookiesArgs = {
  input: ImportCookiesInput;
};


export type MutationImportJournalEntriesArgs = {
  input: ImportJournalEntriesInput;
};


export type MutationImportObsidianNotesArgs = {
  input: ImportObsidianNotesInput;
};


export type MutationRemoveICloudCredentialsArgs = {
  input: RemoveICloudCredentialsInput;
};


export type MutationRemoveSpotifyCredentialsArgs = {
  input: RemoveSpotifyCredentialsInput;
};


export type MutationRequestUserEmailVerificationArgs = {
  input: RequestUserEmailVerificationInput;
};


export type MutationRequestUserPasswordResetArgs = {
  input: RequestUserPasswordResetInput;
};


export type MutationTestMutationArgs = {
  input: TestMutationInput;
};


export type MutationUpdateICloudCredentialsArgs = {
  input: UpdateICloudCredentialsInput;
};


export type MutationUpdateUserEmailArgs = {
  input: UpdateUserEmailInput;
};


export type MutationUpdateUserProfileArgs = {
  input: UpdateUserProfileInput;
};


export type MutationVerifyICloudSecurityCodeArgs = {
  input: VerifyICloudSecurityCodeInput;
};

/** An object with an ID. */
export type Node = {
  /** ID of the object. */
  id: Scalars['ID']['output'];
};

export type NotionComment = {
  __typename?: 'NotionComment';
  createdAt: Scalars['DateTime']['output'];
  id: Scalars['String']['output'];
  modifiedAt: Scalars['DateTime']['output'];
  richText: Scalars['JSON']['output'];
};

export type OAuthCredentials = Node & {
  __typename?: 'OAuthCredentials';
  accessToken?: Maybe<Scalars['String']['output']>;
  /** ID of the object. */
  id: Scalars['ID']['output'];
  name: Scalars['String']['output'];
  refreshToken?: Maybe<Scalars['String']['output']>;
  uid: Scalars['String']['output'];
};

/** An object with an ID. */
export type ObsidianEntry = {
  createdAt: Scalars['DateTime']['output'];
  /** ID of the object. */
  id: Scalars['ID']['output'];
  name: Scalars['String']['output'];
  referencedBy: Array<ObsidianNote>;
  title: Scalars['String']['output'];
  updatedAt: Scalars['DateTime']['output'];
};

export type ObsidianNote = Node & ObsidianEntry & {
  __typename?: 'ObsidianNote';
  aliases: Array<Scalars['String']['output']>;
  blurb?: Maybe<Scalars['String']['output']>;
  content?: Maybe<Scalars['String']['output']>;
  createdAt: Scalars['DateTime']['output'];
  /** ID of the object. */
  id: Scalars['ID']['output'];
  isPublished: Scalars['Boolean']['output'];
  modifiedAt: Scalars['DateTime']['output'];
  name: Scalars['String']['output'];
  plainBlurb?: Maybe<Scalars['String']['output']>;
  referencedBy: Array<ObsidianNote>;
  references: Array<ObsidianEntry>;
  tags: Array<Scalars['String']['output']>;
  title: Scalars['String']['output'];
  updatedAt: Scalars['DateTime']['output'];
  url: Scalars['String']['output'];
};

/** The connection type for ObsidianNote. */
export type ObsidianNoteConnection = {
  __typename?: 'ObsidianNoteConnection';
  /** A list of edges. */
  edges: Array<ObsidianNoteEdge>;
  /** A list of nodes. */
  nodes: Array<ObsidianNote>;
  /** Information to aid in pagination. */
  pageInfo: PageInfo;
  totalCount: Scalars['Int']['output'];
};

/** An edge in a connection. */
export type ObsidianNoteEdge = {
  __typename?: 'ObsidianNoteEdge';
  /** A cursor for use in pagination. */
  cursor: Scalars['String']['output'];
  /** The item at the end of the edge. */
  node: ObsidianNote;
};

export type ObsidianStub = Node & ObsidianEntry & {
  __typename?: 'ObsidianStub';
  createdAt: Scalars['DateTime']['output'];
  /** ID of the object. */
  id: Scalars['ID']['output'];
  name: Scalars['String']['output'];
  referencedBy: Array<ObsidianNote>;
  title: Scalars['String']['output'];
  updatedAt: Scalars['DateTime']['output'];
};

/** Information about pagination in a connection. */
export type PageInfo = {
  __typename?: 'PageInfo';
  /** When paginating forwards, the cursor to continue. */
  endCursor?: Maybe<Scalars['String']['output']>;
  /** When paginating forwards, are there more items? */
  hasNextPage: Scalars['Boolean']['output'];
  /** When paginating backwards, are there more items? */
  hasPreviousPage: Scalars['Boolean']['output'];
  /** When paginating backwards, the cursor to continue. */
  startCursor?: Maybe<Scalars['String']['output']>;
};

export type Query = {
  __typename?: 'Query';
  activityStatus?: Maybe<Scalars['String']['output']>;
  /** When the server was booted. */
  bootedAt: Scalars['DateTime']['output'];
  /** Kai's contact email. */
  contactEmail: Scalars['String']['output'];
  /** What I'm currently listening to on Spotify! */
  currentlyPlaying?: Maybe<SpotifyCurrentlyPlaying>;
  homepageJournalEntry?: Maybe<JournalEntry>;
  /** Kai's personal iCloud credentials (#securityStartsHere). */
  icloudCredentials?: Maybe<ICloudCredentials>;
  imageBySignedId?: Maybe<Image>;
  journalEntryComments: Array<NotionComment>;
  obsidianNote?: Maybe<ObsidianNote>;
  obsidianNoteByName?: Maybe<ObsidianNote>;
  obsidianNotes: ObsidianNoteConnection;
  passwordStrength: Scalars['Float']['output'];
  /** Kai's JSON Resume (https://jsonresume.org/). */
  resume: Scalars['JSON']['output'];
  /** Spotify OAuth credentials. */
  spotifyCredentials?: Maybe<OAuthCredentials>;
  testEcho: Scalars['String']['output'];
  /** Kai's current timezone. */
  timezone: Timezone;
  user?: Maybe<User>;
  /** The currently authenticated user. */
  viewer?: Maybe<User>;
};


export type QueryHomepageJournalEntryArgs = {
  id?: InputMaybe<Scalars['ID']['input']>;
};


export type QueryImageBySignedIdArgs = {
  signedId: Scalars['String']['input'];
};


export type QueryJournalEntryCommentsArgs = {
  entryId: Scalars['ID']['input'];
};


export type QueryObsidianNoteArgs = {
  id: Scalars['ID']['input'];
};


export type QueryObsidianNoteByNameArgs = {
  name: Scalars['String']['input'];
};


export type QueryObsidianNotesArgs = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Int']['input']>;
  last?: InputMaybe<Scalars['Int']['input']>;
  modifiedAfter?: InputMaybe<Scalars['DateTime']['input']>;
  modifiedBefore?: InputMaybe<Scalars['DateTime']['input']>;
};


export type QueryPasswordStrengthArgs = {
  password: Scalars['String']['input'];
};


export type QueryTestEchoArgs = {
  text?: InputMaybe<Scalars['String']['input']>;
};


export type QueryUserArgs = {
  id: Scalars['ID']['input'];
};

/** Autogenerated input type of RemoveICloudCredentials */
export type RemoveICloudCredentialsInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
};

/** Autogenerated return type of RemoveICloudCredentials. */
export type RemoveICloudCredentialsPayload = {
  __typename?: 'RemoveICloudCredentialsPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  success: Scalars['Boolean']['output'];
};

/** Autogenerated input type of RemoveSpotifyCredentials */
export type RemoveSpotifyCredentialsInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
};

/** Autogenerated return type of RemoveSpotifyCredentials. */
export type RemoveSpotifyCredentialsPayload = {
  __typename?: 'RemoveSpotifyCredentialsPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  success: Scalars['Boolean']['output'];
};

/** Autogenerated input type of RequestUserEmailVerification */
export type RequestUserEmailVerificationInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  email: Scalars['String']['input'];
};

/** Autogenerated return type of RequestUserEmailVerification. */
export type RequestUserEmailVerificationPayload = {
  __typename?: 'RequestUserEmailVerificationPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  success: Scalars['Boolean']['output'];
};

/** Autogenerated input type of RequestUserPasswordReset */
export type RequestUserPasswordResetInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  email: Scalars['String']['input'];
};

/** Autogenerated return type of RequestUserPasswordReset. */
export type RequestUserPasswordResetPayload = {
  __typename?: 'RequestUserPasswordResetPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  success: Scalars['Boolean']['output'];
};

export enum ScottkitSignalType {
  Break = 'BREAK',
  Panic = 'PANIC',
  Rand = 'RAND'
}

export type SpotifyAlbum = {
  __typename?: 'SpotifyAlbum';
  id: Scalars['String']['output'];
  imageUrl?: Maybe<Scalars['String']['output']>;
  name: Scalars['String']['output'];
  url: Scalars['String']['output'];
};

export type SpotifyArtist = {
  __typename?: 'SpotifyArtist';
  id: Scalars['String']['output'];
  name: Scalars['String']['output'];
  url: Scalars['String']['output'];
};

export type SpotifyCurrentlyPlaying = {
  __typename?: 'SpotifyCurrentlyPlaying';
  progressMilliseconds: Scalars['Int']['output'];
  track: SpotifyTrack;
};

export type SpotifyLyricLine = {
  __typename?: 'SpotifyLyricLine';
  isExplicit: Scalars['Boolean']['output'];
  startTimeMilliseconds: Scalars['Int']['output'];
  words: Scalars['String']['output'];
};

export type SpotifyTrack = {
  __typename?: 'SpotifyTrack';
  album: SpotifyAlbum;
  artists: Array<SpotifyArtist>;
  durationMilliseconds: Scalars['Int']['output'];
  id: Scalars['String']['output'];
  lyrics?: Maybe<Array<SpotifyLyricLine>>;
  name: Scalars['String']['output'];
  url: Scalars['String']['output'];
};

export type Subscription = {
  __typename?: 'Subscription';
  activityStatus?: Maybe<Scalars['String']['output']>;
  /** What I'm currently listening to on Spotify! */
  currentlyPlaying?: Maybe<SpotifyCurrentlyPlaying>;
  testSubscription: Scalars['Int']['output'];
};

export type TestModel = {
  __typename?: 'TestModel';
  birthday?: Maybe<Scalars['Date']['output']>;
  id: Scalars['ID']['output'];
  name: Scalars['String']['output'];
};

/** Autogenerated input type of TestMutation */
export type TestMutationInput = {
  birthday?: InputMaybe<Scalars['Date']['input']>;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  name: Scalars['String']['input'];
};

/** Autogenerated return type of TestMutation. */
export type TestMutationPayload = {
  __typename?: 'TestMutationPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors?: Maybe<Array<InputFieldError>>;
  model?: Maybe<TestModel>;
  success: Scalars['Boolean']['output'];
};

export type Timezone = {
  __typename?: 'Timezone';
  abbreviation: Scalars['String']['output'];
  name: Scalars['String']['output'];
  offset: Scalars['String']['output'];
  offsetMinutes: Scalars['Int']['output'];
};

/** Autogenerated input type of UpdateICloudCredentials */
export type UpdateICloudCredentialsInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  email: Scalars['String']['input'];
  password: Scalars['String']['input'];
};

/** Autogenerated return type of UpdateICloudCredentials. */
export type UpdateICloudCredentialsPayload = {
  __typename?: 'UpdateICloudCredentialsPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors?: Maybe<Array<InputFieldError>>;
  icloudCredentials?: Maybe<ICloudCredentials>;
  success: Scalars['Boolean']['output'];
};

/** Autogenerated input type of UpdateUserEmail */
export type UpdateUserEmailInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  currentPassword: Scalars['String']['input'];
  email: Scalars['String']['input'];
};

/** Autogenerated return type of UpdateUserEmail. */
export type UpdateUserEmailPayload = {
  __typename?: 'UpdateUserEmailPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors?: Maybe<Array<InputFieldError>>;
  success: Scalars['Boolean']['output'];
  user?: Maybe<User>;
};

/** Autogenerated input type of UpdateUserProfile */
export type UpdateUserProfileInput = {
  avatar?: InputMaybe<ImageInput>;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  name: Scalars['String']['input'];
};

/** Autogenerated return type of UpdateUserProfile. */
export type UpdateUserProfilePayload = {
  __typename?: 'UpdateUserProfilePayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors?: Maybe<Array<InputFieldError>>;
  success: Scalars['Boolean']['output'];
  user?: Maybe<User>;
};

export type User = Node & {
  __typename?: 'User';
  avatar?: Maybe<Image>;
  email: Scalars['String']['output'];
  /** ID of the object. */
  id: Scalars['ID']['output'];
  isOwner: Scalars['Boolean']['output'];
  name: Scalars['String']['output'];
  unverifiedEmail?: Maybe<Scalars['String']['output']>;
};

/** Autogenerated input type of VerifyICloudSecurityCode */
export type VerifyICloudSecurityCodeInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  code: Scalars['String']['input'];
};

/** Autogenerated return type of VerifyICloudSecurityCode. */
export type VerifyICloudSecurityCodePayload = {
  __typename?: 'VerifyICloudSecurityCodePayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  icloudCredentials: ICloudCredentials;
  success: Scalars['Boolean']['output'];
};
