import type { ImportsMap, PresetName } from "unplugin-auto-import/types";

export const imports: Array<ImportsMap | PresetName> = [
  "react",
  {
    "@apollo/client": [
      "useQuery",
      "useLazyQuery",
      "useSubscription",
      "useMutation",
    ],
    "@inertiajs/inertia-react": ["Link", "usePage"],
    "@mantine/core": [
      "useMantineTheme",
      "useMantineColorScheme",
      "Alert",
      "Anchor",
      "Badge",
      "Box",
      "Button",
      "Card",
      "Center",
      "Chip",
      "Container",
      "Divider",
      "Group",
      "List",
      "MediaQuery",
      "Space",
      "Stack",
      "Text",
      "TextInput",
      "Title",
      "Tooltip",
      "Transition",
    ],
    "@mantine/form": ["useForm"],
    "@mantine/hooks": ["useDocumentVisibility", "useMediaQuery"],
    "@mantine/notifications": ["showNotification"],
    "@mantine/modals": ["openModal", "closeAllModals"],
    "lodash-es": ["first", "mapKeys", "omit"],
    luxon: ["DateTime"],
    "react-use": ["useEvent"],
    "~/components": ["Head", "AppLayout", "CenterLayout", "PageHeader"],
    "~/helpers": [
      "resolve",
      "getMeta",
      "requireMeta",
      "formatError",
      "formatApolloError",
      "useApolloErrorCallback",
      "useDateTime",
      "useMounted",
      "layoutWithData",
      "usePageErrors",
      "usePageProps",
      "usePageData",
      "useRouter",
    ],
  },
];
