- how principles and practices shape peoples lives
- how important it is to simply show up
- increasing the surface area for self-connection
- posture and practicing the way you show up for yourself
- '"trying" vs "letting things unfold"'
- how the world needs you to come alive
- honouring yourself in connnection with others
- seeing the beauty in your own fear and awkwardness
