- startups and building something that people want
- the alternate life path
- ruby on rails and programming
- community-building and culture
- cultivating a continuous felt sense of love and playfulness
- noticing that when i see the world with optimism, the world sees me with optimism in return
- how to fight my insecurities
- how to deal with starting all over again, all the time
