basics:
  name: Kai Xie
  summary: |-
    Full-stack software engineer, designer, and hacker.
  profiles:
    - network: GitHub
      username: hulloitskai
      url: https://github.com/hulloitskai
  email: hello@itskai.me
work:
  # - name: Next Canada
  #   position: Next36 Entrepreneur (2023 Cohort)
  #   url: https://www.nextcanada.com/next-36/
  #   startDate: 2023-03
  #   endDate: 2023-08
  #   summary: >-
  #     An intensive entrepreneurship program to grow Canada's most promising
  #     founders.
  #   highlights:
  #     - Selected as one of the 36 entrepreneurs for the 2023 cohort from over
  #       500 applicants.
  #     - Founded an AI startup, while receiving coaching on
  #       objective-setting, pitching, fundraising, and more.
  - name: Freelance Software Consulting
    position: Full-Stack Engineer
    startDate: 2022-10
    highlights:
      - >-
        Developed a touch interface for an aromatherapy medical device, used
        in pain relief clinical trials.
      - >-
        Deployed & secured (SAML SSO) a data science toolkit for a Canadian
        telecommunications network.
      - >-
        Conceptualized and built a website to help Canadian homeowners understand
        their home's energy efficiency, explore potential retrofits (and
        relevant government rebates), and find contractors.
  - name: Promptly (NEXT36 2023)
    position: Co-Founder & CTO
    url: https://askpromptly.ai
    startDate: 2023-03
    endDate: 2023-08
    highlights:
      - >-
        Designed and built a platform with Ruby on Rails, React, & OpenAI APIs
        to help product teams understand their users' behaviours by talking to
        their users at scale with conversational AI.
      - >-
        Engineered an AI system to conduct effective interviews; this involved
        training multiple models, each with one area of responsibility (e.g. one
        model decides whether to follow-up on an user's response or to move onto
        the next question; another ensures questions are unbiased and
        non-hypothetical).
      - >-
        Built an initial prototype in 2 weeks; secured first paying customer
        after 4 weeks.
  - name: Playces
    position: Co-Founder & CTO
    url: https://playces.in
    startDate: 2019-04
    endDate: 2022-10
    highlights:
      - >-
        Conceptualized and built a platform to modernize independent tourism
        businesses, enabling them to take bookings & accept payments online,
        simplify operations, and reach more customers.
      - >-
        Gave partners observability into under-utilized resources, and
        improved operational agility; our customer champion increased
        bookings by 250%, tripled number of experiences offered, and
        increased revenue per booking by 40% after switching from AirBnB & Fare
        Harbor to Playces.
      - >-
        Researched, designed, built, deployed, and iterated on
        product and technology stack (Postgres, ElasticSearch, Kubernetes,
        HubSpot, Sentry, Stripe) as the sole engineering/product lead.
  - name: Universe
    position: Software Developer (Co-op)
    url: http://universe.com
    startDate: 2019-01
    endDate: 2019-04
    highlights:
      - >-
        Developed internal tooling with Golang for orchestrating on-demand staging
        environments for Universe's microservices stack on Kubernetes, to power
        code review and QA flows.
      - >-
        Researched and implemented optimizations to half the amount of time it
        took to launch a staging stack, reducing both wait times in our QA
        workflow, as well as our GCP bills.
  - name: ConsenSys
    position: Software Developer (Co-op)
    url: https://consensys.net
    startDate: 2018-05
    endDate: 2018-08
    highlights:
      - >-
        Developed a team management app using React, MongoDB, and Neo4J to
        facilitate objective-setting and improve role clarity at large-scale
        decentralized organizations.
      - >-
        Architected a system to store and visualize a large, complex graph of
        relational data using Neo4J (a graph database) and D3, while using redux
        and websockets to synchronize state.
education:
  - institution: University of Waterloo
    area: Computer Science
    studyType: Bachelor
    startDate: 2017-09
    endDate: 2019-04
  - institution: Wilfrid Laurier University
    area: Business Administration
    studyType: Bachelor
    startDate: 2017-09
    endDate: 2018-04
skills:
  - name: Front-End
    keywords:
      - HTML
      - CSS
      - JavaScript
      - React
      - GraphQL
      - JSON
      - Mapbox
      - SSR
      - SEO
      - PWA
      - Websockets
  - name: Back-End
    keywords:
      - Golang
      - NodeJS
      - NextJS
      - Ruby On Rails
      - Postgres
      - MongoDB
      - ETL
      - Caching
      - Parallellism
      - Webhooks
      - ElasticSearch
      - Security & XSS Prevention
      - Kubernetes
      - CI/CD
  - name: Mobile
    keywords:
      - React Native
      - Expo
      - Flutter
      - Swift
      - Java & Kotlin
      - XCode
      - Android Studio
  - name: Design
    keywords:
      - Figma
      - Design Systems
      - Animations
      - Human-Centered Design
      - User Interviewing
