basics:
  name: Kai Xie
  summary: Full-stack software engineer, designer, and hacker
  profiles:
    - network: GitHub
      username: hulloitskai
      url: https://github.com/hulloitskai
    - network: LinkedIn
      username: hulloitskai
      url: https://linkedin.com/in/hulloitskai
  email: hello@itskai.me
  # location: { city: "Vancouver/Remote" }
work:
  - name: Lumos
    position: Senior Software Engineer
    startDate: 2023-11
    endDate: 2024-03
    highlights:
      - >-
        Led design & development of AI systems (GPT-4-vision) to parse and
        analyze software purchase orders, invoices, and transactions. This
        system converted a fully-manual multi-hour document analysis process to
        a 10-minute automated procedure requiring only a couple of manual
        interventions.
      - >-
        Iterated on a platform for managing software vendor agreements and
        right-sizing contracts to save clients 15% annually (on average) during
        software contract renewals.
    url: https://lumos.com
  # - name: Next Canada
  #   position: Next36 Entrepreneur (2023 Cohort)
  #   url: https://www.nextcanada.com/next-36/
  #   startDate: 2023-03
  #   endDate: 2023-08
  #   summary: >-
  #     An intensive entrepreneurship program to grow Canada's most promising
  #     founders.
  #   highlights:
  #     - Selected as one of the 36 entrepreneurs for the 2023 cohort from over
  #       500 applicants.
  #     - Founded an AI startup, while receiving coaching on
  #       objective-setting, pitching, fundraising, and more.
  - name: Freelance Consulting
    position: Full-stack Software Engineer
    startDate: 2022-10
    endDate: 2023-02
    highlights:
      - >-
        Implemented an accessible touch and audio interface for a novel
        medical device, to be used in an unpcoming NIH-funded
        clinical trial to treat opioid use disorder.
      - >-
        Deployed and secured (SAML SSO) a business intelligence toolkit for a
        Canadian telecommunications network, enabling sales teams to do
        market analysis supported by live data.
  - name: Promptly (NEXT36 2023)
    position: Co-Founder & CTO
    url: https://askpromptly.ai
    startDate: 2023-03
    endDate: 2023-08
    highlights:
      - >-
        Designed and built a platform with Ruby on Rails, React, & OpenAI APIs
        to help product teams understand their users' behaviours by talking to
        their users at scale with conversational AI.
      - >-
        Engineered end-to-end system to conduct effective interviews; trained
        and coordinated multiple models to handle different areas of
        responsibility (e.g. user response analysis, bias avoidance, determining
        follow-up approach) while interviewing users.
      - >-
        Built initial version in 2 weeks; secured first paying customer
        in 4 weeks.
      - >-
        Sold to direct competitor Outset (YC 23).
  - name: Playces
    position: Co-Founder & CTO
    startDate: 2019-04
    endDate: 2022-10
    highlights:
      - >-
        Designed and built a platform to modernize independent tourism
        businesses, enabling them to take bookings & accept payments with Stripe,
        simplify operations, and reach more customers.
      - >-
        Gave partners observability into under-utilized resources, and
        improved operational agility; our customer champion increased
        bookings by 250%, tripled number of experiences offered, and
        increased revenue per booking by 40% after switching from AirBnB & Fare
        Harbor to Playces.
      - >-
        Researched, designed, built, deployed, and iterated on
        product and technology stack (Ruby on Rails, Postgres, ElasticSearch,
        Kubernetes, Sentry, AWS) as the sole engineering/product lead.
  - name: Universe
    position: Software Developer
    url: http://universe.com
    startDate: 2019-01
    endDate: 2019-04
    highlights:
      - >-
        Led the development of an internal tool (written in Golang) for
        orchestrating on-demand staging environments for our microservices stack
        on Kubernetes, saving the QA team 10+ hours per week.
      - >-
        Optimized GCP deployment process to cut the time it takes to launch a
        staging environment by 50%.
education:
  - institution: University of Waterloo
    area: Computer Science
    studyType: Bachelor
    startDate: 2017-09
    endDate: 2019-04
  - institution: Wilfrid Laurier University
    area: Business Administration
    studyType: Bachelor
    startDate: 2017-09
    endDate: 2018-04
skills:
  - name: Front-end
    keywords:
      - React (6yoe)
      - GraphQL (4yoe)
      - SCSS
      - PWA
      - Mapbox
      - SSR
      - SEO
      - Analytics / Heatmaps
  - name: Back-end
    keywords:
      - Ruby on Rails (4yoe)
      - Postgres (4yoe)
      - Kubernetes (2yoe)
      - Golang (2yoe)
      - NextJS (2yoe)
      - OAuth
      - ElasticSearch
      - MongoDB
      - ETL
      - Redis
      - Parallellism
      - CI/CD
      - NodeJS
  - name: Mobile
    keywords:
      - Flutter
      - React Native
      - Expo
      - XCode
      - Swift
      - Java
      - Kotlin
      - Android Studio
  - name: Design
    keywords:
      - Figma
      - Design Patterns
      - Animations
      - Human-Centered Design
      - User Personas
