basics:
  name: Kai Xie
  summary: |-
    I'm a generalist software engineer, amateur systems designer, a creative and a tinkerer/hacker.
    I like to build things that make people smile!
  profiles:
    - network: GitHub
      username: hulloitskai
      url: https://github.com/hulloitskai
  email: hello@itskai.me
work:
  - name: Playces
    position: Chief Technology Officer
    url: https://playces.in
    startDate: 2019-04
    endDate: 2022-10
    highlights:
      - >-
        Designed and built a platform in Ruby on Rails and React to modernize
        independent tourism businesses, enabling them to display availability
        and receive bookings online, accept payments and send invoices (Stripe),
        automate manual processes (booking questions, automatic emails, built-in
        CRM, operations dashboard) and reach more customers (travel communities
        with social feed and media embeds).
      - >-
        Gave our partners observability into under-utilized resources and the
        operational agility to really grow; one customer champion increased
        bookings by 250%, tripled the number of experiences offered, and
        increased revenue per booking by 40% after switching from AirBnB & Fare
        Harbor to Playces.
      - >-
        Researched, designed, built, deployed, and iterated on our
        product and technology stack (Postgres, ElasticSearch, Kubernetes,
        HubSpot, Mailgun, Sentry, etc.) as the sole engineering/product person.
  - name: Universe
    position: Software Developer Intern
    url: http://universe.com
    startDate: 2019-01
    endDate: 2019-04
    highlights:
      - >-
        Write a CLI tool in Go for orchestrating on-demand staging environments
        for our microservices stack on Kubernetes, which powered our code review
        and QA flows. Investigated the operational limitations
        of the existing Rundeck-based systems and used these insights to design
        a spiritual successor.
      - >-
        Researched and implemented  optimizations to half the amount of time it
        took to launch a staging stack, reducing both wait times in our QA
        workflow, as well as our GCP bills.
      - >-
        Supported product development by troubleshooting unexpected deployment
        failures
      - >-
        Investigated security concerns and implemented solutions to mitigate
        them.

  - name: ConsenSys
    position: Software Developer Intern
    url: https://consensys.net
    startDate: 2018-04
    endDate: 2018-08
    highlights:
      - >-
        Developed a team management webapp using React, MongoDB, and Neo4J to
        support the operation of decentralized organizations like ConsenSys.
      - >-
        Worked with relationship-heavy data sets using graph databases, and
        architected a scalable data-heavy applications using Redux and
        websockets.
education:
  - institution: University of Waterloo
    area: Computer Science
    studyType: Bachelor
    startDate: 2017-09
    endDate: 2019-04
  - institution: Wilfrid Laurier University
    area: Business Administration
    studyType: Bachelor
    startDate: 2017-09
    endDate: 2018-04
skills:
  - name: Front-End Web Development
    keywords:
      - HTML
      - CSS
      - JavaScript
      - React
      - GraphQL
      - JSON
      - Mapbox
      - SSR
      - SEO
      - PWA
      - Realtime, Live
  - name: Back-End Web Development
    keywords:
      - Golang
      - NodeJS
      - NextJS
      - Ruby On Rails
      - SQL, NoSQL, Graph Databases
      - ETL
      - Caching
      - Performance
      - Parallellism
      - APIs, Integrations
      - Webhooks
      - Text & Geo Search
      - Security, Permissions, XSS Prevention
  - name: DevOps, Infra
    keywords:
      - Golang
      - Kubernetes, CRDs, Operators, GitOps
      - Docker
      - Containerization
      - CI & CD
      - Terraform
      - AWS
      - GCP
      - DigitalOcean
      - ElasticSearch
      - Postgres
      - Redis
      - Site Reliability
      - Security & Hardening
  - name: Mobile
    keywords:
      - React Native
      - Expo
      - Flutter
      - Swift
      - Java & Kotlin
      - XCode
      - Android Studio
  - name: Design, UX, UI
    keywords:
      - Figma
      - Sketch
      - Design Systems
      - Animations
      - Human-Centered Design
      - User Interviewing
