basics:
  name: Kai Xie
  summary: |-
    Generalist software engineer, designer, and hacker.
  profiles:
    - network: GitHub
      username: hulloitskai
      url: https://github.com/hulloitskai
  email: hello@itskai.me
work:
  - name: Prompt Labs
    position: Co-Founder
    url: https://askpromptly.ai
    startDate: 2023-03
    endDate: 2023-08
    highlights:
      - >-
        Designed and built a platform that helps product teams understand their
        users' behaviour, by talking to their users at scale with conversational
        AI.
      - >-
        Engineered an AI system to conduct effective interviews; this includes
        training multiple models, each with one area of responsibility (e.g. one
        model decides whether to follow-up on an user's response or to move onto
        the next question; another ensures questions are unbiased and
        non-hypothetical).
      - >-
        Built an initial prototype in 2 weeks; got our first paying customer
        after 4 weeks.
  - name: Playces
    position: Co-Founder & CTO
    url: https://playces.in
    startDate: 2019-04
    endDate: 2022-10
    highlights:
      - >-
        Designed and built a platform to modernize independent tourism
        businesses, enabling them to display availability and receive bookings,
        accept payments and send invoices, automate manual processes (booking
        questions, automatic emails, built-in CRM, operations dashboard) and
        reach more customers (travel communities with a social feed and media
        embeds).
      - >-
        Gave our partners observability into under-utilized resources and the
        operational agility to really grow; our customer champion increased
        bookings by 250%, tripled number of experiences offered, and
        increased revenue per booking by 40% after switching from AirBnB & Fare
        Harbor to Playces.
      - >-
        Researched, designed, built, deployed, and iterated on
        product and technology stack (Postgres, ElasticSearch, Kubernetes,
        HubSpot, Sentry, Stripe) as the sole engineering/product lead.
  - name: Universe
    position: Software Developer (Co-op)
    url: http://universe.com
    startDate: 2019-01
    endDate: 2019-04
    highlights:
      - >-
        Developed internal tooling for orchestrating on-demand staging
        environments for Universe's microservices stack on Kubernetes, to power
        code review and QA flows.
      - >-
        Researched and implemented optimizations to half the amount of time it
        took to launch a staging stack, reducing both wait times in our QA
        workflow, as well as our GCP bills.
  - name: ConsenSys
    position: Software Developer (Co-op)
    url: https://consensys.net
    startDate: 2018-05
    endDate: 2018-08
    highlights:
      - >-
        Developed a team management app using React, MongoDB, and Neo4J to
        support the operation of decentralized organizations like ConsenSys.
      - >-
        Worked with relationship-heavy data sets using graph databases, and
        Architected a system to store and visualize relational using Redux and
        websockets.
education:
  - institution: Next 36
    area: 2023 Cohort
    startDate: 2023-03
    endDate: 2023-08
  - institution: University of Waterloo
    area: Computer Science
    studyType: Bachelor
    startDate: 2017-09
    endDate: 2019-04
  - institution: Wilfrid Laurier University
    area: Business Administration
    studyType: Bachelor
    startDate: 2017-09
    endDate: 2018-04
skills:
  - name: Front-End Web Development
    keywords:
      - HTML
      - CSS
      - JavaScript
      - React
      - GraphQL
      - JSON
      - Mapbox
      - SSR
      - SEO
      - PWA
      - Realtime, Live
  - name: Back-End Web Development
    keywords:
      - Golang
      - NodeJS
      - NextJS
      - Ruby On Rails
      - PostgreSQL, MongoDB, Neo4J
      - ETL
      - Caching
      - Parallellism
      - APIs & Integrations
      - Webhooks
      - ElasticSearch
      - Security & XSS Prevention
      - Kubernetes
      - CI/CD
  - name: Mobile
    keywords:
      - React Native
      - Expo
      - Flutter
      - Swift
      - Java & Kotlin
      - XCode
      - Android Studio
  - name: Design, UX, UI
    keywords:
      - Figma
      - Sketch
      - Design Systems
      - Animations
      - Human-Centered Design
      - User Interviewing
