test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

amazon:
  service: S3
  access_key_id: <%= Rails.application.credentials.s3&.access_key_id %>
  secret_access_key: <%= Rails.application.credentials.s3&.secret_access_key %>
  region: <%= Rails.application.credentials.s3&.region %>
  bucket: <%= Rails.application.credentials.s3&.bucket %>

cloudflare:
  service: S3
  endpoint: <%= Rails.application.credentials.r2.endpoint %>
  access_key_id: <%= Rails.application.credentials.r2.access_key_id %>
  secret_access_key: <%= Rails.application.credentials.r2.secret_access_key %>
  bucket: <%= Rails.application.credentials.r2.bucket %>
  region: auto
