# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Activity::ClearStatusJob`.
# Please instead update this file by running `bin/tapioca dsl Activity::ClearStatusJob`.

class Activity::ClearStatusJob
  class << self
    sig { returns(T.any(Activity::ClearStatusJob, FalseClass)) }
    def perform_later; end

    sig { void }
    def perform_now; end
  end
end
