name: check

on:
  - push
  - pull_request

env:
  OVERMIND_VERSION: "2.4.0"
  OWNER_EMAIL: test@example.com

jobs:
  check:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:15-3.3
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: yarn
          cache-dependency-path: "**/yarn.lock"
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Set up Overmind
        run: |
          sudo apt-get install tmux \
            && sudo curl -Lo /usr/bin/overmind.gz https://github.com/DarthSim/overmind/releases/download/v$OVERMIND_VERSION/overmind-v$OVERMIND_VERSION-linux-amd64.gz \
            && sudo gzip -d /usr/bin/overmind.gz \
            && sudo chmod u+x /usr/bin/overmind \
            && sudo chown $(whoami) /usr/bin/overmind
      - name: Set up environment
        run: bin/setup
      - name: Check formatting
        run: bin/fmt
      - name: Check lints
        run: bin/lint
      - name: Run tests
        run: bin/test
